### ISSUE TITLE
Resultado errado

### ISSUE THREAD

**Issue by DouglasdeMoura** [sitegui/topCalc#6]
A expressão sqrt(2)^2-2 deve ser igual a zero, porém a calculadora retorna 4.440892e-16.

**Comment by sitegui** [comment]
@DouglasdeMoura , a top calc não trabalha com números não racionais de forma exata.

Ou seja, [ao fazer `sqrt(2)`](https://github.com/sitegui/topCalc/blob/master/Fracao.js#L149-L154) o resultado é representado por um [double](https://en.wikipedia.org/wiki/Double-precision_floating-point_format), por isso o resultado apresenta o erro observado.

Estou fechando essa issue pois esse comportamento é esperado. Se houver algo mais, só reabrir aqui.
